<tr>
    <td><?php echo $income->getId(); ?></td>
    <td><?php echo $income->getDate(); ?></td>
    <td><?php echo $income->getAmount(); ?></td>
    <td><?php echo $income->getCurrency(); ?></td>
    <td>$<?php echo $curentUsdAmount; ?></td>
    <td>
        <a href="<?php echo $this->url('bablo/default', ['controller' => 'accounting', 'action' => 'edit-income', 'id' => $income->getId()]); ?>" class="btn btn-info">Edit</a>
        <button class="btn btn-danger">Delete</button>
    </td> 
</tr>