<div class="row">
    
    
    <div class="col-md-6">
        
<?php
//$form->setAttribute('action', $this->url('album', array('action' => 'add')));
$form->setAttribute('action', '/bablo/accounting/edit-income');
echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();
?>

    </div>
    <div class="col-md-3">
        <div id="messages" class="text-danger border-danger"></div>
    </div>
</div>
<script>
    $().ready(function(){
        $('#income').submit(function(e, o){
            $.post('<?php echo $this->url('validate', ['action' => 'income'])?>', 
            {
                amount: $('#income [name=amount]').val(),
                date: $('#income [name=date]').val(),
                source_id: [$('#income [name=source_id\\[\\]] option:selected').val()],
            },
            function (data) {
                e.preventDefault();
            });
        });
    });
</script>
<script src="/js/main.js"></script>