<?php
$this->headTitle("Income Report");
$this->headStyle(<<<EOD
        .search_form {
            background: #ffd25e;
            border-radius: 5px;
EOD
        );
?>
<?php echo $this->form()->openTag($form);?>
<div class="row search_form">
    <div class="col-md-4">
<?php
echo $this->babloFormRow($form->get('month_from'), 'form-group'); 
echo $this->babloFormRow($form->get('month_to'), 'form-group'); 
?>
    </div>
    <div class="col-md-4">
        <?php
        echo $this->babloFormRow($form->get('min_amount'), 'form-group');
        echo $this->babloFormRow($form->get('currency'), 'form-group'); 
        echo $this->formSubmit($form->get('submit'));
        ?>
    </div>
    <div class="col-md-4">
        <?php
        echo $this->babloFormRow($form->get('max_amount'), 'form-group');
        echo $this->babloFormRow($form->get('source'), 'form-group'); 
        ?>
    </div>
</div>
<?php

echo $this->form()->closeTag();
?>
<div>Selected month: <?php echo 'not ready';?></div>
<table id="incomes_table" class="table table-striped table-bordered table-condensed">
    <tr>
        <th>ID</th>
        <th>Date</th>
        <th>Amount</th>
        <th>Currency</th>
        <th>USD Amount</th>
        <td>Actions</td>
        
    </tr>
<?php
    $usdAmount=0;
    
    foreach ($incomes as $income) {
        $usdAmount+=$income->getUsdAmount();
        $curentUsdAmount=round($income->getUsdAmount(),2);
        echo "<tr><td>{$income->getId()}</td>"
        . "<td>{$income->getDate()}</td>"
        . "<td>{$income->getAmount()}</td>"
        . "<td>{$income->getCurrency()}</td>"
        . "<td>\${$curentUsdAmount}</td>"
        . "<td>"
        . "<a href=\"{$this->url('bablo/default', ['controller' => 'accounting', 'action' => 'edit-income', 'id' => $income->getId()])}\" class=\"btn btn-info\">Edit</a>"
        . "<button class=\"btn btn-danger\">Delete</button>"
        . "</td>" 
        . "</tr>";
    }
    
?>
</table>
<div id="new_content"></div>
<div>Total USD Amount: <?php echo round($usdAmount,2);?></div>
<div style="color:red;"><?php echo $message; ?></div>
<script src="/js/main.js"></script>