<div id="wait" style="display: none">
    <div>
        <img src="/img/indicator.gif" />
    </div>
    <div>
        Loading...
    </div>
</div>

<div class="jumbotron">
    <div id="graph-box">
        <canvas id="graph" style="border: solid black 1px; width: 100%; height: 300px;"></canvas>
    </div>
</div>
<div class="row">
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Получено бабла за месяц</h3>
            </div>
            <?php echo $this->summary("monthly-income", "panel-body text-center", '/report/monthlyIncome', 'updateMonthlyIncome'); ?>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Потрачено бабла за месяц</h3>
            </div>
            <?php echo $this->summary("monthly-expence", "panel-body text-center", '/report/monthlyExpence', 'updateMonthlyExpence'); ?>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Баланс за год</h3>
            </div>
            <?php echo $this->summary("annual-balance", "panel-body text-center", '/report/annualBalance', 'updateAnnualBalance'); ?>
            </div>
        </div>
    </div>
</div>
<script>
    var updateMonthlyIncomeinProgress = false;
    var updateMonthlyExpenceinProgress = false;
    var updateAnnualBalanceinProgress = false;
    function updateNumber (data, containerId) {
        var sum = 0;
        $(data.updates).each(function (i, e) {
            sum += Number(e.usdAmount);
        });
        $('#' + containerId).html('<h1>$' + sum + '</h1>');
    }
    
    function updateMonthlyIncome(data) {
        updateNumber(data, 'monthly-income');
        updateMonthlyIncomeinProgress = false;
    }
    function updateMonthlyExpence(data) {
        updateNumber(data, 'monthly-expence');
        updateMonthlyExpenceinProgress = false;
    }
    
    function updateAnnualBalance(data) {
        updateNumber(data, 'annual-balance');
        updateAnnualBalanceinProgress = false;
    }
</script>
<script src="/js/graph.js"></script>