<div class="jumbotron">
    <h1>Главная страница</h1>
</div>
<div class="row">
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Почувствуйте разницу между баблом и прочим фуфлом</h3>
            </div>
            <div class="panel-body">
                Наш проект круче всех остальных. Как говорится, лучшее - враг хорошего.
            </div>
        </div>
    </div>
    
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Считай бабло не отходя от кассы</h3>
            </div>
            <div class="panel-body">
                Удобная система подсчета бабла!
                <?php
                if ($user) {
                    echo $user->getName();
                }
                ?>
            </div>
        </div>
    </div>
    
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Присоединяйся и греби бабло лопатой!</h3>
            </div>
            <div class="panel-body">
                <?php
                //$form->setAttribute('action', $this->url('album', array('action' => 'add')));
                $login->setAttribute('action', '/bablo/index/login');
                echo $this->form()->openTag($login);
                echo $this->formCollection($login);
                echo $this->form()->closeTag();
                ?>
            </div>
        </div>
    </div>
</div>