<html>
    <head>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headScript(); ?>
        <?php echo $this->headStyle(); ?>
        <meta charset="utf-8" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
        <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.13.0/jquery.validate.js"></script>
        <script src="js/js.js"></script>
    </head>
    <body> 
        <div class="container">
            <nav class="navbar navbar-inverse">
                <div class="collapse navbar-collapse">
                    <?php                
                    echo $this->navigation('navigation')->menu()->setUlClass('nav navbar-nav');
                    ?>
                </div>
            </nav>
        </div>
        <div class="container">

            <header>
                
            </header>
            <?php echo $this->content; ?>
            <footer>
                <p>&copy; 2014 - Computer Academy STEP, Donetsk</p>
            </footer>
        </div>

    </body>
    <?php echo $this->inlineScript(); ?>
</html>

